version: '2'
services:
    web:
        build: .
        ports:
        - "80:5000"
        volumes:
            - .:/app
        command: flask run
        environment:
          - DATABASE_URL=postgres://postgres:$POSTGRES_PASSWORD@psql:5432/postgres
          - MONGODB_URI=mongodb://$MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_PASSWORD@mongo:27017/mongodb
    psql:
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD
    mongo:
        image: mongo:latest
        environment:
            - MONGO_INITDB_ROOT_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD
